name: CI

on:
  push:
    branches:
      - master
  pull_request:
  # schedule:
  #   - cron: "0 23 * * 6"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        node_version:
          - "14"
          - "12"
          - "10"
        include:
          - os: "macos-latest"
            node_version: "10"
          - os: "windows-latest"
            node_version: "10"

    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Dependencies
        run: yarn

      # - name: Download Artifact
      #   uses: actions/download-artifact@master
      #   with:
      #     name: dist
      #     path: dist

      - name: Run Test
        run: yarn test-coverage

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        if: success()
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Sending webhook to Coveralls
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master

      - name: Install Dependencies
        run: yarn

      - name: Build Package
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
